export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

export const TODO_CREATE = 'TODO_CREATE';
export const TODO_SET_COMPLETE = 'TODO_SET_COMPLETE';
export const TODO_EDIT = 'TODO_EDIT';
